Feat/bg initiator generic
lblod/app-digitaal-loket pull request #289
Opened 2022-11-28 13:10 UTC by nbittich

2022-12-02 09:35 UTC, claire-lovisa commented on docker-compose.yml
> +  delta-producer-background-jobs-initiator-generic:
Two minor remarks but:
1. Wouldn't it make more sense to put this service in the `# DELTA GENERAL` section ?
2. Couldn't we just omit the `-generic` in the same ? Especially if it's in the DELTA GENERAL section, in speaks for itself ?

2022-12-02 09:37 UTC, claire-lovisa commented on docker-compose.yml
> +  delta-producer-background-jobs-initiator-generic:
The docker-compose.dev.yml file should also be updated, to add the `restart: "no"` on the generic initiator and remove the specific job initiators

2022-12-02 12:17 UTC, claire-lovisa requested changes
Without the update on the docker-compose.dev.yml, the tack doesn't start :grin: Other than that it seems to be working fine !

2022-12-02 12:17 UTC, claire-lovisa commented on docker-compose.yml
> +  delta-producer-background-jobs-initiator-generic:
The docker-compose.dev.yml file should also be updated, to add the restart: "no" on the generic initiator and remove the specific job initiators

2023-05-17 09:06 UTC, nbittich commented on config/delta-producer/background-jobs-initiator/config.json
> +[
@claire-lovisa sorry this branch wasn't meant to be reviewed. we do it in the harvester first to test if everything's ok there.

2024-02-09 15:36 UTC, aatauil commented
This PR is more then a year old and most likely not needed anymore. Please feel free to reopen it if I am mistaking.

2024-02-09 15:36 UTC, closed without merging