Add flag to poltiezone & hulpverlenigzone besluitenlijst
lblod/app-digitaal-loket pull request #427
Opened 2023-06-16 07:21 UTC by aatauil

2023-06-30 13:06 UTC, cecemel requested changes

2023-06-30 13:06 UTC, cecemel commented on config/migrations/2023/20230613112721-add-politiezone-hulpverleningszone-flag.sparql
> +INSERT {
High level, i would split in smaller migrations

2023-06-30 13:06 UTC, cecemel commented on config/migrations/2023/20230613112721-add-politiezone-hulpverleningszone-flag.sparql
> +    ?form <http://lblod.data.gift/vocabularies/besluit/authenticityType> |
here you could make a separate list of types that need to be exported. That's a one time check you can do, not to check for every separate sbumission. (the walking of this tree is super expensive)

2023-06-30 13:06 UTC, cecemel commented on config/migrations/2023/20230613112721-add-politiezone-hulpverleningszone-flag.sparql
> +    OPTIONAL { ?submissionDocument adms:status ?submissionDocumentStatus . }
not sure why optional are needed, I think any of these optional fails (expect perhaps the attachments) the data is broken.

2023-06-30 13:06 UTC, cecemel commented on config/migrations/2023/20230613112721-add-politiezone-hulpverleningszone-flag.sparql
> +    FILTER ( ?conceptScheme IN (
I think here they are interested in all submissions from the bestuursorganen, so maybe no extra filter needed?

2023-09-14 13:21 UTC, closed without merging

2023-09-14 13:22 UTC, aatauil commented
moved to https://github.com/lblod/app-digitaal-loket/pull/452