Delete AGB Stekene
lblod/app-digitaal-loket pull request #622
Opened 2024-12-12 18:46 UTC by Riadabd

## Ticket ID

OP-3409

## Description

`AGB Stekene` is archived in this OP PR: https://github.com/lblod/app-organization-portal/pull/486 . On the Loket side, we have to delete the organization and its connected data since Loket does not have archival support yet.

## How to Test

### Query the data

Run the following queries to inspect the org's data on a local production backup:
```sparql
SELECT * WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/8d6609b4-1a20-46b8-97ed-150c6d53acd6> {
    ?s ?p ?o .
  }
}
```
```sparql
SELECT * WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/8d6609b4-1a20-46b8-97ed-150c6d53acd6/LoketLB-berichtenGebruiker> {
    ?s ?p ?o .
  }
}
```
```sparql
SELECT * WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/8d6609b4-1a20-46b8-97ed-150c6d53acd6/LoketLB-toezichtGebruiker> {
    ?s ?p ?o .
  }
}
```
```sparql
SELECT * WHERE {
  GRAPH <http://mu.semte.ch/graphs/organizations/8d6609b4-1a20-46b8-97ed-150c6d53acd6/LoketLB-personeelsbeheer> {
    ?s ?p ?o .
  }
}
```
```sparql
SELECT ?p ?o WHERE {
  GRAPH <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/id/bestuurseenheden/8d6609b4-1a20-46b8-97ed-150c6d53acd6> ?p ?o .
  }
}
```
```sparql
SELECT ?g ?s ?p WHERE {
  GRAPH ?g {
    ?s ?p <http://data.lblod.info/id/bestuurseenheden/8d6609b4-1a20-46b8-97ed-150c6d53acd6> .
  }
}
```
```sparql
SELECT DISTINCT ?s WHERE {
  VALUES ?bestuursorganen {
    <http://data.lblod.info/id/bestuursorganen/24d8e602a8ddbe0adf3dea8c40277706>
    <http://data.lblod.info/id/bestuursorganen/dad1789d9b9f8f6cb3c81cc2ca88154f>
    <http://data.lblod.info/id/bestuursorganen/b90d16f2c8043bc20b88da232c0389fc>
    <http://data.lblod.info/id/bestuursorganen/2f27a688e1728c1906a4bbd8670d7810>
  }
  
  GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?bestuursorganen .
  }
}
```

### Run the migration

Run the migration and refresh the results of the queries run above => All results should now be empty with the exception of the query for `/LoketLB-berichtenGebruiker`. In this case, you will still see the `<http://www.semanticdesktop.org/ontologies/2007/01/19/nie#dataSource>` property, which is intended.

2024-12-12 18:49 UTC, Riadabd commented on config/migrations/2024/20241212193803-delete-agb-stekene.sparql
> +  GRAPH <http://mu.semte.ch/graphs/public> {
Specifying `<http://mu.semte.ch/graphs/public>` here and in subsequent lines is to limit the deletion to the public graph and keep the data inside the op landing zone graph (`<http://mu.semte.ch/graphs/landing-zone/op-public>`).

2025-01-22 09:39 UTC, cecemel commented on config/migrations/2024/20241212193803-delete-agb-stekene.sparql
> +# Remove bestuursorganen
This will happen at OP propagation of the deleted data right?

2025-01-22 09:39 UTC, cecemel commented on config/migrations/2024/20241212193803-delete-agb-stekene.sparql
> +# Remove bestuursorganen in tijd
Idem: OP should delete, loket should consume?

2025-01-22 09:40 UTC, cecemel commented on config/migrations/2024/20241212193803-delete-agb-stekene.sparql
> +  GRAPH <http://mu.semte.ch/graphs/public> {
This will happen at OP propagation of the deleted data right?

2025-01-22 09:41 UTC, cecemel commented on config/migrations/2024/20241212193803-delete-agb-stekene.sparql
> +    ?mockPerson ?mockPersonP ?mockPersonO .
Deleteing mock accounts is not needed. If the bestuurseenheid is deleted, https://github.com/lblod/update-bestuurseenheid-mock-login-service takes care of the rest

2025-01-22 09:41 UTC, cecemel requested changes
Thanks, see single comments

2025-01-22 09:55 UTC, Riadabd commented
@cecemel This PR can be closed as it was made when work was still being done on the consumer, and PRs affecting organizations had to be done both on OP and Loket. This is no longer needed now.

2025-01-22 13:35 UTC, closed without merging